---
- name: Update and Install Software
  hosts: all
  become: true
  pre_tasks:
    - name: Install updates (CentOS)
      tags: always
      yum:
        update_cache: yes
        name: '*'
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'

  tasks:
    - name: Install Apache and PHP for Ubuntu servers
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Apache and PHP for CentOS servers
      tags: apache, apache2, httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Start httpd (CentOS)
      tags: apache, centos, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['distribution'] == 'CentOS'

- name: Setup Database Servers
  hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package (CentOS)
      tags: centos, db, mariadb
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Install MariaDB package (Ubuntu)
      tags: db, mariadb, ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Restart and Enable MariaDB
      service:
        name: mariadb
        state: restarted
        enabled: yes

- name: Setup File Servers
  hosts: file_servers
  become: true
  tasks:
    - name: Install Samba package
      tags: samba
      package:
        name: samba
        state: latest

